bin.includes = META-INF/,\
               officeserver-4.0.0.jar,\
               officeserver_default-4.0.0.jar,\
               officeweb-4.0.0.jar,\
               officeweb_configuration-4.0.0.jar,\
               officeweb_resource-4.0.0.jar,\
               officeweb_security-4.0.0.jar,\
               officeweb_template-4.0.0.jar,\
               woof-4.0.0.jar
